export const FACEBOOK_LOGIN_SUCCESS = 'fb_login_success';
export const FACEBOOK_LOGIN_FAIL = 'fb_login_fail';
export const FETCH_JOBS = 'fetch_jobs';
export const LIKE_JOB = 'like_job';
export const CLEAR_LIKED_JOBS = 'clear_liked_jobs';
export const NEW_LOCATION = 'new_location';
export const LOCATION_PERMISSION_DENIED = 'location_denied';
export const NEW_PLACES = 'new_places';
export const REGISTER_EMAIL_CHANGE = 'register_email_changed';
export const REGISTER_PASSWORD_CHANGE= 'register_password_changed'
export const REGISTER_VERIFY_PW_CHANGE = 'register_verify_pw';